# Generated by Django 3.0.5 on 2020-04-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_api', '0002_profilefeeditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilefeeditem',
            name='image_url',
            field=models.CharField(default='https://i.picsum.photos/id/64/4326/2884.jpg', max_length=255),
        ),
    ]
